"""updated simple user table

Revision ID: 79330dab8134
Revises: 1775086a6fd5
Create Date: 2025-10-15 19:54:11.940008

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "79330dab8134"
down_revision: str | Sequence[str] | None = "1775086a6fd5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("username", name=op.f("uq_user_username")),
    )
    op.drop_index(op.f("ix_Users_username"), table_name="Users")
    op.drop_table("Users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Users",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("Users_pkey")),
    )
    op.create_index(op.f("ix_Users_username"), "Users", ["username"], unique=True)
    op.drop_table("user")
    # ### end Alembic commands ###
