"""fixed repr

Revision ID: 8c704b321d85
Revises: e827b24ced56
Create Date: 2025-10-23 20:47:56.304575

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "8c704b321d85"
down_revision: str | Sequence[str] | None = "e827b24ced56"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
