"""updated user table

Revision ID: b1637d28f51b
Revises: 79330dab8134
Create Date: 2025-10-19 16:13:37.632015

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1637d28f51b"
down_revision: str | Sequence[str] | None = "79330dab8134"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _get_user_role():
    return postgresql.ENUM(
        "Admin",
        "FullAccessUser",
        "AuthorizedUser",
        "UnauthorizedUser",
        name="role_enum",
    )


def upgrade() -> None:
    """Upgrade schema."""
    user_role = _get_user_role()
    user_role.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("email", sa.String(), nullable=False))
    op.add_column("user", sa.Column("password", sa.String(), nullable=False))
    op.add_column(
        "user",
        sa.Column(
            "role",
            user_role,
            nullable=False,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "created", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "full_access_deadline",
            sa.TIMESTAMP(),
            server_default=sa.text("(now() + interval '356 days')"),
            nullable=False,
        ),
    )
    op.create_unique_constraint(op.f("uq_user_email"), "user", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_user_email"), "user", type_="unique")
    op.drop_column("user", "full_access_deadline")
    op.drop_column("user", "created")
    op.drop_column("user", "role")
    op.drop_column("user", "password")
    op.drop_column("user", "email")
    # ### end Alembic commands ###
    _get_user_role().drop(op.get_bind())
