"""added association_proxy

Revision ID: b5cfe8407e2d
Revises: e4f1e03e69dd
Create Date: 2025-10-23 21:04:33.888080

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b5cfe8407e2d"
down_revision: str | Sequence[str] | None = "e4f1e03e69dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
