"""Fixed dictlist

Revision ID: bee699f67b8e
Revises: cc00bbc8d4ba
Create Date: 2025-11-21 19:29:09.398905

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bee699f67b8e"
down_revision: str | Sequence[str] | None = "cc00bbc8d4ba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dictlist", "lang_code", existing_type=sa.VARCHAR(length=5), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dictlist", "lang_code", existing_type=sa.VARCHAR(length=5), nullable=False
    )
    # ### end Alembic commands ###
