"""fixed some repr

Revision ID: e4f1e03e69dd
Revises: 8c704b321d85
Create Date: 2025-10-23 20:52:50.811421

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "e4f1e03e69dd"
down_revision: str | Sequence[str] | None = "8c704b321d85"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
