"""fixed id init

Revision ID: e827b24ced56
Revises: cc00bbc8d4ba
Create Date: 2025-10-23 20:21:42.573996

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "e827b24ced56"
down_revision: str | Sequence[str] | None = "cc00bbc8d4ba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
